### ISSUE TITLE
Logging specs fails on specific seeds

### ISSUE THREAD

**Issue by whitemerry** [departurerb/departure#84]
On some specific seeds logging specs fails on `stdout` check.

Sample environment:
- Ruby 2.6.6
- Rails 5.2.0.

Seed 18011: `267 examples, 0 failures, 3 pending`
Seed 27815: `267 examples, 1 failure, 3 pending`

```bash
$ bundle exec rspec --seed 27815
[...]

  1) Departure logging when the migration logging is disabled doesn't send the output to stdout
     Failure/Error:
       expect do
         ActiveRecord::Migrator.new(direction, migration_fixtures, ActiveRecord::SchemaMigration, 1).migrate
       end.to_not output.to_stdout
     
       expected block to not output to stdout, but output "\n   -> Running pt-online-schema-change -h \"localhost\" -P 3306 -u root [filtered_password] --execu...Event  Count\n# ====== =====\n# INSERT     1\nSuccessfully altered `departure_test`.`comments`.\n\n"
     # ./spec/integration_spec.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/integration_spec.rb:31:in `block (4 levels) in <top (required)>'

Finished in 43.38 seconds (files took 1.05 seconds to load)
267 examples, 1 failure, 3 pending
```

Sample GitHub Actions build: #83

**Comment by whitemerry** [comment]
I'll try to take a look at the issue in next few days

**Comment by benlangfeld** [comment]
It took more than a year to get around to it, but there's a fix for this in https://github.com/departurerb/departure/pull/101.
